/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nagarjunareddy' at '10/3/16 11:07 AM' with Gradle 2.13
 *
 * @author nagarjunareddy, @date 10/3/16 11:07 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
